/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorldnewsRouteImport } from './routes/worldnews'
import { Route as TourismRouteImport } from './routes/tourism'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MusicRouteImport } from './routes/music'
import { Route as HealthRouteImport } from './routes/health'
import { Route as EconomyRouteImport } from './routes/economy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksRefreshNewsRouteImport } from './routes/api/public/hooks/refresh-news'

const WorldnewsRoute = WorldnewsRouteImport.update({
  id: '/worldnews',
  path: '/worldnews',
  getParentRoute: () => rootRouteImport,
} as any)
const TourismRoute = TourismRouteImport.update({
  id: '/tourism',
  path: '/tourism',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const EconomyRoute = EconomyRouteImport.update({
  id: '/economy',
  path: '/economy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshNewsRoute =
  ApiPublicHooksRefreshNewsRouteImport.update({
    id: '/api/public/hooks/refresh-news',
    path: '/api/public/hooks/refresh-news',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/economy': typeof EconomyRoute
  '/health': typeof HealthRoute
  '/music': typeof MusicRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/tourism': typeof TourismRoute
  '/worldnews': typeof WorldnewsRoute
  '/api/public/hooks/refresh-news': typeof ApiPublicHooksRefreshNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/economy': typeof EconomyRoute
  '/health': typeof HealthRoute
  '/music': typeof MusicRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/tourism': typeof TourismRoute
  '/worldnews': typeof WorldnewsRoute
  '/api/public/hooks/refresh-news': typeof ApiPublicHooksRefreshNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/economy': typeof EconomyRoute
  '/health': typeof HealthRoute
  '/music': typeof MusicRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sports': typeof SportsRoute
  '/tourism': typeof TourismRoute
  '/worldnews': typeof WorldnewsRoute
  '/api/public/hooks/refresh-news': typeof ApiPublicHooksRefreshNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/economy'
    | '/health'
    | '/music'
    | '/sitemap.xml'
    | '/sports'
    | '/tourism'
    | '/worldnews'
    | '/api/public/hooks/refresh-news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/economy'
    | '/health'
    | '/music'
    | '/sitemap.xml'
    | '/sports'
    | '/tourism'
    | '/worldnews'
    | '/api/public/hooks/refresh-news'
  id:
    | '__root__'
    | '/'
    | '/economy'
    | '/health'
    | '/music'
    | '/sitemap.xml'
    | '/sports'
    | '/tourism'
    | '/worldnews'
    | '/api/public/hooks/refresh-news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EconomyRoute: typeof EconomyRoute
  HealthRoute: typeof HealthRoute
  MusicRoute: typeof MusicRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SportsRoute: typeof SportsRoute
  TourismRoute: typeof TourismRoute
  WorldnewsRoute: typeof WorldnewsRoute
  ApiPublicHooksRefreshNewsRoute: typeof ApiPublicHooksRefreshNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worldnews': {
      id: '/worldnews'
      path: '/worldnews'
      fullPath: '/worldnews'
      preLoaderRoute: typeof WorldnewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourism': {
      id: '/tourism'
      path: '/tourism'
      fullPath: '/tourism'
      preLoaderRoute: typeof TourismRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/economy': {
      id: '/economy'
      path: '/economy'
      fullPath: '/economy'
      preLoaderRoute: typeof EconomyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-news': {
      id: '/api/public/hooks/refresh-news'
      path: '/api/public/hooks/refresh-news'
      fullPath: '/api/public/hooks/refresh-news'
      preLoaderRoute: typeof ApiPublicHooksRefreshNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EconomyRoute: EconomyRoute,
  HealthRoute: HealthRoute,
  MusicRoute: MusicRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SportsRoute: SportsRoute,
  TourismRoute: TourismRoute,
  WorldnewsRoute: WorldnewsRoute,
  ApiPublicHooksRefreshNewsRoute: ApiPublicHooksRefreshNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
